[workspace]
resolver = "2"
members = [
    "Json",
    "CSharp",
    "powershell",
    "Rust",
    "Python",
    "Cpp",
    "Lua",
    "Toml",
    "Markdown",
    "Zig",
    "TypeScript",
    "Terraform",
    "Sql",
    "Bash",
    "Yaml",
    "Html",
    "Css",
    "Go",
    "Dart",
    "ForgeFlow",
    "common",
    "tools/registry-gen",
]
exclude = [
    "ForgeFlow/zed",
]

[workspace.package]
edition = "2021"

[profile.release]
lto = true
strip = true